
-- 1. USERS
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name VARCHAR(100) NOT NULL,
                       phone_number VARCHAR(15) UNIQUE NOT NULL,
                       email VARCHAR(100) UNIQUE NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,
                       role VARCHAR(20) NOT NULL,
                       status VARCHAR(20) NOT NULL
);

-- 2. COURTS
CREATE TABLE courts (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(50) NOT NULL,
                        court_type VARCHAR(30) NOT NULL,
                        status VARCHAR(20) NOT NULL
);


-- 3. PRICE_CONFIGS
CREATE TABLE price_configs (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               court_type VARCHAR(30) NOT NULL,
                               start_time TIME NOT NULL,
                               end_time TIME NOT NULL,
                               price_per_hour NUMERIC(12,2) NOT NULL,
                               is_peak_hour BOOLEAN DEFAULT FALSE
);


-- Tìm bảng giá theo loại sân + khung giờ
CREATE INDEX idx_price_configs_type_time
    ON price_configs (
                      court_type,
                      start_time,
                      end_time
        );


-- 4. DISCOUNT_CONFIGS
CREATE TABLE discount_configs (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  min_months INT NOT NULL,
                                  discount_percent NUMERIC(5,2) NOT NULL,
                                  status VARCHAR(20) DEFAULT 'ACTIVE'
);



-- 5. RECURRING_BOOKINGS
CREATE TABLE recurring_bookings (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    customer_id BIGINT,
                                    court_id BIGINT,
                                    start_date DATE NOT NULL,
                                    end_date DATE NOT NULL,
                                    days_of_week VARCHAR(50) NOT NULL,
                                    start_time TIME NOT NULL,
                                    end_time TIME NOT NULL,
                                    discount_rate NUMERIC(5,2) DEFAULT 0.00,
                                    total_amount NUMERIC(12,2) NOT NULL,
                                    status VARCHAR(20) DEFAULT 'ACTIVE',
                                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                    CONSTRAINT fk_recurring_customer
                                        FOREIGN KEY (customer_id)
                                            REFERENCES users(id),

                                    CONSTRAINT fk_recurring_court
                                        FOREIGN KEY (court_id)
                                            REFERENCES courts(id)
);


-- Tìm các gói đặt cố định của một khách
CREATE INDEX idx_recurring_customer_status
    ON recurring_bookings (
                           customer_id,
                           status
        );

-- Tìm lịch cố định của một sân
CREATE INDEX idx_recurring_court_status
    ON recurring_bookings (
                           court_id,
                           status
        );



-- =========================================================
-- 6. BOOKINGS
-- =========================================================

CREATE TABLE bookings (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          booking_code VARCHAR(20) UNIQUE NOT NULL,
                          customer_id BIGINT,
                          created_by_staff_id BIGINT,
                          recurring_booking_id BIGINT,
                          court_id BIGINT,
                          booking_date DATE NOT NULL,
                          start_time TIME NOT NULL,
                          end_time TIME NOT NULL,
                          court_price NUMERIC(12,2) NOT NULL,
                          service_price NUMERIC(12,2) DEFAULT 0.00,
                          total_amount NUMERIC(12,2) NOT NULL,
                          booking_status VARCHAR(20) NOT NULL,
                          payment_status VARCHAR(20) NOT NULL,
                          payment_method VARCHAR(20),
                          cancel_reason TEXT,
                          expire_at TIMESTAMP,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          paid_at TIMESTAMP,
                          paid_by_staff_id BIGINT,

                          CONSTRAINT fk_booking_customer
                              FOREIGN KEY (customer_id)
                                  REFERENCES users(id),

                          CONSTRAINT fk_booking_created_by_staff
                              FOREIGN KEY (created_by_staff_id)
                                  REFERENCES users(id),

                          CONSTRAINT fk_booking_recurring
                              FOREIGN KEY (recurring_booking_id)
                                  REFERENCES recurring_bookings(id),

                          CONSTRAINT fk_booking_court
                              FOREIGN KEY (court_id)
                                  REFERENCES courts(id),

                          CONSTRAINT fk_booking_paid_by_staff
                              FOREIGN KEY (paid_by_staff_id)
                                  REFERENCES users(id)
);

-- Tìm booking thuộc sân nào ngày nào và theo giờ kèm 3 trạng thái.
CREATE INDEX idx_bookings_active_schedule
    ON bookings (
                 court_id,
                 booking_date,
                 start_time,
                 end_time
        )
    WHERE booking_status IN (
    'PENDING',
    'CONFIRMED',
    'CHECKED_IN'
);

-- Tìm booking theo ngày và trạng thái
CREATE INDEX idx_bookings_date_status
    ON bookings (
                 booking_date,
                 booking_status
        );

-- Tìm lịch sử booking của khách
CREATE INDEX idx_bookings_customer_created
    ON bookings (
                 customer_id,
                 created_at DESC
        );

--Tìm bookings thuốc recurring
CREATE INDEX idx_bookings_recurring_date
    ON bookings (
                 recurring_booking_id,
                 booking_date
        );

-- Tìm bookings đã hết hạn
CREATE INDEX idx_bookings_pending_expire
    ON bookings (
                 expire_at
        )
    WHERE booking_status = 'PENDING';


-- Tìm bookings dã thanh toán và lọc theo thời gian
CREATE INDEX idx_bookings_paid_created
    ON bookings (
                 created_at
        )
    WHERE payment_status = 'PAID';

-- 7. SERVICES
CREATE TABLE services (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          category VARCHAR(30) NOT NULL,
                          unit_price NUMERIC(12,2) NOT NULL,
                          status VARCHAR(20) DEFAULT 'ACTIVE'
);


-- 8. BOOKING_SERVICES
CREATE TABLE booking_services (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  booking_id BIGINT,
                                  service_id BIGINT,
                                  quantity INT NOT NULL,
                                  price_at_booking NUMERIC(12,2) NOT NULL,
                                  subtotal NUMERIC(12,2) NOT NULL,

                                  CONSTRAINT fk_booking_services_booking
                                      FOREIGN KEY (booking_id)
                                          REFERENCES bookings(id),

                                  CONSTRAINT fk_booking_services_service
                                      FOREIGN KEY (service_id)
                                          REFERENCES services(id)
);


-- Lấy dịch vụ của một booking để in ra trong bill chẳng hạn
CREATE INDEX idx_booking_services_booking
    ON booking_services (
                         booking_id
        );


-- 9. FAQS
CREATE TABLE faqs (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      question TEXT NOT NULL,
                      answer TEXT NOT NULL,
                      category VARCHAR(50),
                      updated_by BIGINT,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                      CONSTRAINT fk_faq_updated_by
                          FOREIGN KEY (updated_by)
                              REFERENCES users(id)
);


-- Lọc FAQ theo category
CREATE INDEX idx_faqs_category
    ON faqs (
             category
        );